name: Deploy Frontend to GitHub Pages

# Kapan robot ini bekerja? Saat ada push ke branch 'main'
on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Menggunakan Node.js versi LTS yang stabil

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🛠️ Build Project (Vite)
        run: npm run build

      - name: 🚀 Deploy ke Branch gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Melempar isi folder dist hasil build ke gh-pages
